// ==========================================
// PM DASHBOARD V2
// ==========================================

function renderPM() {

    pageContent.innerHTML = `

    <!-- ==========================================
         PM PAGE
    ========================================== -->

    <div class="pm-page">

        <!-- ==========================================
             HEADER
        ========================================== -->

        <section class="pm-header">

            <div class="pm-header-left">

                <h1>
                    Preventive Maintenance
                </h1>

                <p>

                    Schedule, monitor and manage preventive maintenance
                    across all biomedical equipment from one centralized
                    calendar.

                </p>

            </div>

            <div class="pm-header-right">

                <img
                    src="/static/assets/pm_calendar.png"
                    alt="Preventive Maintenance"
                    class="pm-header-image"
                >

            </div>

        </section>

        <!-- ==========================================
             CALENDAR
        ========================================== -->

        <section class="pm-calendar-card">

            <div class="pm-calendar-toolbar">

                <div class="pm-calendar-navigation">

                    <button id="pmPrevMonth">

                        <i data-lucide="chevron-left"></i>

                    </button>

                    <h2 id="pmCurrentMonth">

                        July 2026

                    </h2>

                    <button id="pmNextMonth">

                        <i data-lucide="chevron-right"></i>

                    </button>

                </div>

                <button
                    class="pm-today-btn"
                    id="pmTodayButton">

                    Today

                </button>

            </div>

            <div id="pmCalendar">

                <!-- Calendar generated by pmCalendar.js -->

            </div>

        </section>

        <!-- ==========================================
             CALENDAR LEGEND
        ========================================== -->

        <section class="pm-legend">

            <div class="legend-item">

                <span class="legend-dot scheduled"></span>

                Scheduled

            </div>

            <div class="legend-item">

                <span class="legend-dot due"></span>

                Due Today

            </div>

            <div class="legend-item">

                <span class="legend-dot overdue"></span>

                Overdue

            </div>

            <div class="legend-item">

                <span class="legend-dot completed"></span>

                Completed

            </div>

            <div class="legend-item">

                <span class="legend-dot empty"></span>

                No PM

            </div>

        </section>

        <!-- ==========================================
             KPI CARDS
        ========================================== -->

        <section
            id="pmKpiCards"
            class="pm-kpi-section">

        </section>

        <!-- ==========================================
             UPCOMING PM
        ========================================== -->

        <section
            id="pmUpcomingSection"
            class="pm-section">

        </section>

        <!-- ==========================================
             OVERDUE PM
        ========================================== -->

        <section
            id="pmOverdueSection"
            class="pm-section">

        </section>

        <!-- ==========================================
             PM HISTORY
        ========================================== -->

        <section
            id="pmHistorySection"
            class="pm-section">

        </section>
        <!-- ==========================================
            PM DRAWER
        ========================================== -->

        <div
            id="pmDrawerOverlay"
            class="pm-drawer-overlay">

            <div
                id="pmDrawer"
                class="pm-drawer">

                <div class="pm-drawer-header">

                    <div>

                        <h2>
                            Schedule Preventive Maintenance
                        </h2>

                        <p>

                            Create a preventive maintenance schedule.

                        </p>

                    </div>

                    <button
                        id="pmDrawerClose"
                        class="pm-drawer-close">

                        <i data-lucide="x"></i>

                    </button>

                </div>

                <div class="pm-drawer-body">

                <!-- Date -->

                <div class="pm-form-group">

                    <label>Date</label>

                    <input
                        id="pmDate"
                        type="text"
                        readonly
                    >

                </div>

                <!-- Department -->

                <div class="pm-form-group">

                    <label>Department</label>

                    <select id="pmDepartment">

                        <option value="">
                            Select Department
                        </option>

                    </select>

                </div>

                <!-- Equipment -->

                <div class="pm-form-group">

                    <label>Equipment</label>

                    <select id="pmEquipment">

                        <option value="">
                            Select Equipment
                        </option>

                    </select>

                </div>

                <!-- Engineer -->

                <div class="pm-form-group">

                    <label>Biomedical Engineer</label>

                    <select id="pmEngineer">

                        <option value="">
                            Assign Engineer
                        </option>

                    </select>

                </div>

                <!-- Frequency -->

                <div class="pm-form-group">

                    <label>Frequency</label>

                    <select id="pmFrequency">

                        <option value="30">
                            Every 30 Days
                        </option>

                        <option value="90">
                            Every 90 Days
                        </option>

                        <option value="180">
                            Every 180 Days
                        </option>

                        <option value="365">
                            Every Year
                        </option>

                    </select>

                </div>

                <!-- Remarks -->

                <div class="pm-form-group">

                    <label>Remarks</label>

                    <textarea
                        id="pmRemarks"
                        rows="5"
                        placeholder="Additional remarks..."
                    ></textarea>

                </div>

                <div class="pm-drawer-footer">

                    <button
                        id="pmCancelButton"
                        class="secondary-btn">

                        Cancel

                    </button>

                    <button
                        id="pmScheduleButton"
                        class="primary-btn">

                        Schedule PM

                    </button>

                </div>

            </div>

        </div>
    </div>

    `;

    lucide.createIcons();

    // Calendar engine (next phase)
    initializePMCalendar();

    initializePMDrawer();

}